# Generated by Django 4.2.7 on 2023-11-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='D:\\django\\Online Doctor\\static\\img\\blog.jpg', upload_to='user_uploads/blogs'),
        ),
    ]
