# Generated by Django 4.2.7 on 2023-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='../static/img/blog.jpg', upload_to='user_uploads/blogs'),
        ),
    ]
