# Generated by Django 4.2.7 on 2023-12-06 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date_time_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_time_start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
