# Generated by Django 4.2.7 on 2023-11-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialities',
            name='slug',
        ),
    ]
